project:
  type: website
  output-dir: public/slides
  render:
    - "!index.qmd"
    - "!about.qmd"

format:
  mpim-revealjs:
      width: 1245
      height: 700
      navigation-mode: linear
      transition: none
