name: wbenv

channels:
  - anaconda
  - conda-forge
  - defaults

dependencies:
  - requests
  - xarray
  - pandas
  - rioxarray
  - cartopy
  - intake
  - colorama
  - aiohttp
  - ipython

pip:
  - easygems